
package client.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyService", targetNamespace = "http://myservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyService {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateNum", targetNamespace = "http://myservice/", className = "client.GenerateNum")
    @ResponseWrapper(localName = "generateNumResponse", targetNamespace = "http://myservice/", className = "client.GenerateNumResponse")
    @Action(input = "http://myservice/MyService/generateNumRequest", output = "http://myservice/MyService/generateNumResponse")
    public int generateNum();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "loginMethod", targetNamespace = "http://myservice/", className = "client.LoginMethod")
    @ResponseWrapper(localName = "loginMethodResponse", targetNamespace = "http://myservice/", className = "client.LoginMethodResponse")
    @Action(input = "http://myservice/MyService/loginMethodRequest", output = "http://myservice/MyService/loginMethodResponse")
    public String loginMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
